//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class LECTOR_DETALLE
    {
        public string ID { get; set; }
        public int ITEM { get; set; }
        public string IDPRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual LECTOR LECTOR { get; set; }
    }
}
