//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string IDUSUARIO { get; set; }
        public string CLAVE { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
    }
}
