//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Entidad;
using System.Data.Entity.Core.EntityClient;

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OKSYSTEMEntities : DbContext
    {
        public OKSYSTEMEntities(String abc)
            :base(abc)
        {
        }

        public static OKSYSTEMEntities Create(string providerConnectionString)
        {
            var entityBuilder = new EntityConnectionStringBuilder();

            // use your ADO.NET connection string
            entityBuilder.ProviderConnectionString = providerConnectionString;

            entityBuilder.Provider = "System.Data.SqlClient";

            // Set the Metadata location.
            entityBuilder.Metadata = "res://*/Model.csdl|res://*/Model.ssdl|res://*/Model.msl";

            return new OKSYSTEMEntities(entityBuilder.ConnectionString);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASIG_TDOCUMENTO> ASIG_TDOCUMENTO { get; set; }
        public virtual DbSet<LECTOR> LECTOR { get; set; }
        public virtual DbSet<LECTOR_DETALLE> LECTOR_DETALLE { get; set; }
        public virtual DbSet<RESPONSABLE> RESPONSABLE { get; set; }
        public virtual DbSet<TDOCUMENTO> TDOCUMENTO { get; set; }
        public virtual DbSet<TDOCUMENTO_SERIE> TDOCUMENTO_SERIE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
